require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MultipleExpectations:
  Enabled: false
